#!/bin/bash

if [[ -z "${BASH_SOURCE[1]}" ]]; then
    >&2 echo "This script cannot be used alone, it must be included by another script"
    exit 1
fi

if [[ -z "$2" ]]; then
    PIDFILE="$PWD/`basename ${BASH_SOURCE[1]}`.pid"
else
    PIDFILE="$PWD/`basename ${BASH_SOURCE[1]}`_$2.pid"
fi

if [[ -s $PIDFILE ]]; then
    PID=`cat $PIDFILE`
fi

if [[ ! -z $PID ]] && (ps -p$PID -o pid= > /dev/null 2>&1); then
    IS_RUNNING=1
else
    IS_RUNNING=0
fi

if [[ $IS_RUNNING -eq 1 ]] && (kill -0 $PID 2> /dev/null); then
    IS_KILLABLE=1
else
    IS_KILLABLE=0
fi

case $1 in
    start)
        if [[ $IS_RUNNING -eq 1 ]]; then
            >&2 echo "It looks like the process cannot be started by `whoami`"
            exit 1
        fi

        ../../php-start $PHP_COMMAND > $PIDFILE

        ;;
    stop)
        if [[ $IS_RUNNING -eq 0 || $IS_KILLABLE -eq 0 ]]; then
            >&2 echo "It looks like the process cannot be stopped by `whoami`"
            exit 1
        fi

        ../../php-stop < $PIDFILE; rm $PIDFILE

        ;;
    *)
        echo "usage: command {start|stop} {node_id}" ;;
esac

exit 0
