imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

framework:
    secret:         "%secret%"
    default_locale: "%locale%"

# RabbitMQ Configuration
old_sound_rabbit_mq:
    connections:
        default:
            lazy: true
    producers:
        ping:
            connection:       default
    consumers:
        ping:
            connection:       default
            exchange_options: { name: 'amq.direct', type: direct }
            queue_options:    { name: 'hello' }
            callback:         ping_consumer