#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once __DIR__.'/bootstrap.php';

$application = $app['console'];
$application->add(new \PingPong\Command\SendCommand());
$application->add(new \PingPong\Command\BounceCommand());
$application->run();
